os:
  - linux
services:
  - docker
language: node_js
node_js:
  - "6.9.5"
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
cache:
  yarn: true
  directories:
    - $HOME/.yarn-cache
    - node_modules
branches:
  only:
  - master
before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Repo for Yarn
  - npm install -g @angular/cli
  - npm install 
install:
  - yarn install
script:
  - ng test --watch false
  - ng e2e
notifications:
  webhooks:
    on_success: change
    on_failure: always
    on_start: false